var MapDataStore = (function () {
    return {
        select: {
            "items": [
                {"id": 709, "code": "sankt-peterburg",
                    "name": "&quot;VERONA&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona14.html",
                    "department": "&quot;VERONA&quot;",
                    "images": '/upload/resize_cache/iblock/0d7/153_113_1/img_0325.jpg',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "ТЦ &quot;Мебель WOOD&quot; Дальневосточный пр., 14"},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 448-20-15",
                    "work": {"time": "с 11:00 до 21:00", "day": "Ежедневно"},
                    "location": {"lat": 59.9110190016, "lng": 30.4434800148}
                },
                {"id": 9973, "code": "sankt-peterburg",
                    "name": "VERONA mobili", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili-2911.html",
                    "department": "VERONA mobili",
                    "images": '/upload/iblock/d88/point.png',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "Ленинский пр-кт, д. 114 "},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 643-05-07",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 59.852426748536, "lng": 30.243403315544}
                },
                {"id": 711, "code": "sankt-peterburg",
                    "name": "&quot;Великая Мебель Испании&quot; ", "stationId": "0", "stationName": "",
                    "url": "/buy/velikaya-mebel-ispanii423.html",
                    "department": "&quot;Великая Мебель Испании&quot; ",
                    "images": '/upload/resize_cache/iblock/699/153_113_1/ nrrkhm.jpg',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "г. Пушкин, Оранжерейная, 12"},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 466-47-88",
                    "work": {"time": "пн - сб с 11:00 до 20:00, вс с 12:00 до 18:00", "day": ""},
                    "location": {"lat": 59.7173052, "lng": 30.4057738}
                },
                {"id": 708, "code": "sankt-peterburg",
                    "name": "&quot;Великая Мебель Испании&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/velikaya-mebel-ispanii662.html",
                    "department": "&quot;Великая Мебель Испании&quot;",
                    "images": '/upload/resize_cache/iblock/9ba/153_113_1/lady.jpg',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "Васильевский Остров, 13-я линия, д.72  "},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 327-61-61",
                    "work": {"time": "", "day": "Ежедневно"},
                    "location": {"lat": 59.9462451547, "lng": 30.2642816305}
                },
                {"id": 707, "code": "sankt-peterburg",
                    "name": "&quot;Элит-мебель - 1&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/elit-mebel-1651.html",
                    "department": "&quot;Элит-мебель - 1&quot;",
                    "images": '/upload/resize_cache/iblock/4a3/153_113_1/dsc_0007.jpg',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "ул. Марата, 61"},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 375-25-08; 370-71-56",
                    "work": {"time": "с 11:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 59.9220135, "lng": 30.3462352}
                },
                {"id": 705, "code": "sankt-peterburg",
                    "name": "&quot;Элит-мебель - 2&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/elit-mebel-2906.html",
                    "department": "&quot;Элит-мебель - 2&quot;",
                    "images": '/upload/resize_cache/iblock/138/153_113_1/dsc_0024.jpg',
                    "address": {"address-line-1": " г. Санкт-Петербург",
                        "address-line-2": "ул. Варшавская, 3, 4-й этаж, секция 433, ТЦ &quot;Мебельный Континент&quot;"},
                    "cityname": "г. Санкт-Петербург",
                    "phone": "(812) 337-17-63",
                    "work": {"time": "с 11:00 до 21:00", "day": "Ежедневно"},
                    "location": {"lat": 59.8813575871, "lng": 30.3108930588}
                },
                {"id": 9730, "code": "astana",
                    "name": "г. Астана", "stationId": "0", "stationName": "",
                    "url": "/buy/europrestige971.html",
                    "department": "г. Астана",
                    "images": '/upload/resize_cache/iblock/35d/153_113_1/00.jpg',
                    "address": {"address-line-1": " г. Астана",
                        "address-line-2": "ул. Сарыарка, д. 31/2"},
                    "cityname": "г. Астана",
                    "phone": "(7172) 307-888",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 51.1485287811, "lng": 71.4265072346}
                },
                {"id": 10250, "code": "petropavlovsk-kamchatskiy",
                    "name": "Театр Интерьера", "stationId": "0", "stationName": "",
                    "url": "/buy/teatr-interera.html",
                    "department": "Театр Интерьера",
                    "images": '/upload/resize_cache/iblock/e68/153_113_1/1.JPG',
                    "address": {"address-line-1": " г. Петропавловск-Камчатский",
                        "address-line-2": "ул. Проспект Циолковского, д. 40 "},
                    "cityname": "г. Петропавловск-Камчатский",
                    "phone": "(831) 47-99-99",
                    "work": {"time": "Пн. - Пт.: 10:00 – 19:00, Сб. – Вс.: 11:00 – 18:00", "day": ""},
                    "location": {"lat": 53.056112180275, "lng": 158.66659998894}
                },
                {"id": 10001, "code": "tambov",
                    "name": "&quot;Юнион&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/yunion.html",
                    "department": "&quot;Юнион&quot;",
                    "images": '/upload/iblock/02c/default_logo.png',
                    "address": {"address-line-1": " г. Тамбов",
                        "address-line-2": "ул. Советская, д. 34"},
                    "cityname": "г. Тамбов",
                    "phone": "(4752) 75-51-12",
                    "work": {"time": "пн - сб с 09:30 до 20:00; вс - выходной", "day": ""},
                    "location": {"lat": 52.705060010792, "lng": 41.470478475094}
                },
                {"id": 10003, "code": "lipetsk",
                    "name": "&quot;Юнион&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/yunion-lipetsk.html",
                    "department": "&quot;Юнион&quot;",
                    "images": '/upload/iblock/bbb/default_logo.png',
                    "address": {"address-line-1": " г. Липецк",
                        "address-line-2": "Площадь Заводская, д. 1"},
                    "cityname": "г. Липецк",
                    "phone": "(4742) 36-49-49",
                    "work": {"time": "пн - сб с 09:30 до 20:00; вс - выходной", "day": ""},
                    "location": {"lat": 52.634757479918, "lng": 39.663509130478}
                },
                {"id": 10004, "code": "penza",
                    "name": "&quot;Юнион&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/yunion-penza.html",
                    "department": "&quot;Юнион&quot;",
                    "images": '/upload/iblock/442/default_logo.png',
                    "address": {"address-line-1": " г. Пенза",
                        "address-line-2": "ул. Плеханова, д. 34"},
                    "cityname": "г. Пенза",
                    "phone": "(8412) 205-204",
                    "work": {"time": "пн - сб с 09:30 до 20:00; вс - выходной", "day": ""},
                    "location": {"lat": 53.199368352944, "lng": 45.010731518269}
                },
                {"id": 10005, "code": "n-novgorod",
                    "name": "&quot;Юнион&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/yunion-nnovgorod.html",
                    "department": "&quot;Юнион&quot;",
                    "images": '/upload/iblock/aa8/default_logo.png',
                    "address": {"address-line-1": " г. Н. Новгород",
                        "address-line-2": "Бульвар Мира, д. 17а"},
                    "cityname": "г. Н. Новгород",
                    "phone": "(831) 277-51-95",
                    "work": {"time": "пн - сб с 09:30 до 20:00; вс - выходной", "day": ""},
                    "location": {"lat": 56.328762545676, "lng": 43.954474925995}
                },
                {"id": 10268, "code": "magnitogorsk",
                    "name": "&quot;МИЛАНО&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/milano.html",
                    "department": "&quot;МИЛАНО&quot;",
                    "images": '/upload/resize_cache/iblock/d18/153_113_1/фасад МИЛАНО.jpg',
                    "address": {"address-line-1": " г. Магнитогорск",
                        "address-line-2": "пр-кт Карла Маркса, д. 141"},
                    "cityname": "г. Магнитогорск",
                    "phone": "(3519) 31-96-20; (909) 097-55-99",
                    "work": {"time": "пн - пт с 10:00 до 20:00, сб с 10:00 до 19:00, вс - выходной", "day": ""},
                    "location": {"lat": 53.384441832068, "lng": 58.979780673981}
                },
                {"id": 9766, "code": "irkutsk",
                    "name": "VERONA", "stationId": "0", "stationName": "",
                    "url": "/buy/verona.html",
                    "department": "VERONA",
                    "images": '/upload/resize_cache/iblock/300/153_113_1/image-18-09-14-03-09.jpeg',
                    "address": {"address-line-1": " г. Иркутск",
                        "address-line-2": "ул. А. Невского, д. 58"},
                    "cityname": "г. Иркутск",
                    "phone": "(3952) 533-225",
                    "work": {"time": "с 10:00 до 20:00", "day": "ежедневно"},
                    "location": {"lat": 52.269169299211, "lng": 104.31362450123}
                },
                {"id": 9518, "code": "orenburg",
                    "name": "VERONA mobili", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/227/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Оренбург",
                        "address-line-2": "ш. Шарлынское, д. 1"},
                    "cityname": "г. Оренбург",
                    "phone": "(3532) 54-02-45",
                    "work": {"time": "с 10:00 - до 22:00", "day": "ежедневно"},
                    "location": {"lat": 51.8535941877, "lng": 55.1407241821}
                },
                {"id": 9519, "code": "saratov",
                    "name": "&quot;Салон Кей&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/kay-beauty.html",
                    "department": "&quot;Салон Кей&quot;",
                    "images": '/upload/resize_cache/iblock/3e2/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Саратов",
                        "address-line-2": "ул. Чернышевского, 203."},
                    "cityname": "г. Саратов",
                    "phone": "(8452) 28-54-37",
                    "work": {"time": "пн. - пт. с 10:00 до 19:00; сб. 10:00 до 16:00; вс. выходной", "day": ""},
                    "location": {"lat": 51.5162207304, "lng": 46.0069656372}
                },
                {"id": 9522, "code": "n-chelny",
                    "name": "&quot;VERONA&quot; кухни & мебель", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-kitchen-furniture.html",
                    "department": "&quot;VERONA&quot; кухни & мебель",
                    "images": '/upload/resize_cache/iblock/147/153_113_1/IMG-008.JPG',
                    "address": {"address-line-1": " г. Н. Челны",
                        "address-line-2": "пр. Набережночелнинский, д. 5а"},
                    "cityname": "г. Н. Челны",
                    "phone": "(8552) 33-33-06",
                    "work": {"time": "", "day": "пн. - сб. с 10:00 до 19:00; вс. с 10:00 до 16:00"},
                    "location": {"lat": 55.743081295, "lng": 52.4100959301}
                },
                {"id": 9524, "code": "kaliningrad",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design-kaliningrad.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/ae9/153_113_1/Вход.jpg',
                    "address": {"address-line-1": " г. Калининград",
                        "address-line-2": "Московский проспект, д. 99-109"},
                    "cityname": "г. Калининград",
                    "phone": "(4012) 7777-90",
                    "work": {"time": "пн. - сб.: с 10:00 до 20:00, вс.: с 10:00 до 17:00", "day": ""},
                    "location": {"lat": 54.7095425803, "lng": 20.5241560936}
                },
                {"id": 9528, "code": "vladivostok",
                    "name": "&quot;Пятый уровень&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/level-five.html",
                    "department": "&quot;Пятый уровень&quot;",
                    "images": '/upload/resize_cache/iblock/68f/153_113_1/logo.gif',
                    "address": {"address-line-1": " г. Владивосток",
                        "address-line-2": "ул. Пограничная, д. 15, мебельный салон &quot;Пятый уровень&quot;"},
                    "cityname": "г. Владивосток",
                    "phone": "",
                    "work": {"time": "", "day": "пн. - пт. с 10:00 до 18:00, сб. 11:00 -18:00, вс. выходной"},
                    "location": {"lat": 43.1239155526, "lng": 131.880885959}
                },
                {"id": 9595, "code": "ekaterinburg",
                    "name": "VERONA mobili", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili-ekaterinburg.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/a6c/153_113_1/Unica Fragment 8.jpg',
                    "address": {"address-line-1": " г. Екатеринбург",
                        "address-line-2": "ул. Студенческая, д. 11, Мебельный центр Галерея 11, 4 этаж"},
                    "cityname": "г. Екатеринбург",
                    "phone": "(343) 286-73-92",
                    "work": {"time": "с 10:00 до 21:00", "day": "ежедневно "},
                    "location": {"lat": 56.8504093776, "lng": 60.6622767448}
                },
                {"id": 9857, "code": "nalchik",
                    "name": "&quot;Toscana mobili&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/toscana-mobili.html",
                    "department": "&quot;Toscana mobili&quot;",
                    "images": '/upload/resize_cache/iblock/af1/153_113_1/01.jpg',
                    "address": {"address-line-1": " г. Нальчик",
                        "address-line-2": "пр. Шогенцукова, д. 19а"},
                    "cityname": "г. Нальчик",
                    "phone": "(8662) 77-38-53, (928) 711-48-87, (988) 7-22222-8",
                    "work": {"time": "пн. - сб. с 10:00 до 18:00; вс. выходной", "day": ""},
                    "location": {"lat": 43.481737220521, "lng": 43.607246875763}
                },
                {"id": 650, "code": "minsk",
                    "name": "&quot;Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona424.html",
                    "department": "&quot;Верона&quot;",
                    "images": '/upload/resize_cache/iblock/2ad/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Минск",
                        "address-line-2": "г. Минск, ул. Д. Сердича, 11"},
                    "cityname": "г. Минск",
                    "phone": "+375 (29) 695-58-58",
                    "work": {"time": "пн - пт: с 10:00 до 20:00; сб: с 10:00 до 18:00", "day": ""},
                    "location": {"lat": 53.9129002488, "lng": 27.4866583583}
                },
                {"id": 651, "code": "almaty",
                    "name": "г. Алматы", "stationId": "0", "stationName": "",
                    "url": "/buy/studiya-verona950.html",
                    "department": "г. Алматы",
                    "images": '/upload/resize_cache/iblock/760/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Алматы",
                        "address-line-2": "г. Алматы ул. Толе би 187"},
                    "cityname": "г. Алматы",
                    "phone": "(727) 379-67-77",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 43.2520464, "lng": 76.8976262}
                },
                {"id": 654, "code": "arkhangelsk",
                    "name": "&quot;VERONA mobili&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili700.html",
                    "department": "&quot;VERONA mobili&quot;",
                    "images": '/upload/resize_cache/iblock/906/153_113_1/P1010766.JPG',
                    "address": {"address-line-1": " г. Архангельск",
                        "address-line-2": "ул. Гайдара, 55, ТВЦ &quot;Мебельная Империя&quot;"},
                    "cityname": "г. Архангельск",
                    "phone": "(8182) 46-22-42",
                    "work": {"time": "пн. - пт. с 10:00 до 18:00; сб. 11:00 до 16:00; вс. выходной", "day": ""},
                    "location": {"lat": 64.5511565, "lng": 40.544175}
                },
                {"id": 655, "code": "astrakhan",
                    "name": "&quot;Мебель и Кухни&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/lyuks538.html",
                    "department": "&quot;Мебель и Кухни&quot;",
                    "images": '/upload/resize_cache/iblock/c8e/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Астрахань",
                        "address-line-2": "пл. Джона Рида д. 7, корп. 1"},
                    "cityname": "г. Астрахань",
                    "phone": "(8512) 50-21-97",
                    "work": {"time": "пн - сб с 10:00 до 19:00; вс с 10:00 до 16:00", "day": ""},
                    "location": {"lat": 46.3369248808, "lng": 48.0404931307}
                },
                {"id": 656, "code": "bryansk",
                    "name": "&quot;Респект&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/respekt161.html",
                    "department": "&quot;Респект&quot;",
                    "images": '/upload/resize_cache/iblock/36b/153_113_1/1.JPG',
                    "address": {"address-line-1": " г. Брянск",
                        "address-line-2": "ул. Красноармейская, д. 128, ТЦ &quot;Мебель&Дом&quot;"},
                    "cityname": "г. Брянск",
                    "phone": "(4832) 62-04-46",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 53.2432361, "lng": 34.3420989}
                },
                {"id": 660, "code": "vladikavkaz",
                    "name": "&quot;Zetta&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/zetta891.html",
                    "department": "&quot;Zetta&quot;",
                    "images": '/upload/resize_cache/iblock/f28/153_113_1/jpg.jpeg',
                    "address": {"address-line-1": " г. Владикавказ",
                        "address-line-2": "Проспект Коста, д.217"},
                    "cityname": "г. Владикавказ",
                    "phone": "(8672) 55-02-44",
                    "work": {"time": "", "day": "Ежедневно"},
                    "location": {"lat": 43.0474558, "lng": 44.6658064}
                },
                {"id": 661, "code": "vladimir",
                    "name": "ЧП &quot;Гущин&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/chp-gushchin574.html",
                    "department": "ЧП &quot;Гущин&quot;",
                    "images": '/upload/resize_cache/iblock/b60/153_113_1/dsc01013.jpg',
                    "address": {"address-line-1": " г. Владимир",
                        "address-line-2": "пр-т Ленина, 42"},
                    "cityname": "г. Владимир",
                    "phone": "(4922) 44-39-38",
                    "work": {"time": "пн. - пт.  с 10:00 до 19:00; сб. - вс. с 10:00 до 18:00", "day": ""},
                    "location": {"lat": 56.1192851, "lng": 40.3572036}
                },
                {"id": 9622, "code": "voronezh",
                    "name": "Дом мебели &quot;Калипсо&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/dom-mebeli-kalipso.html",
                    "department": "Дом мебели &quot;Калипсо&quot;",
                    "images": '/upload/resize_cache/iblock/7d5/153_113_1/IMG_2295.jpg',
                    "address": {"address-line-1": " г. Воронеж",
                        "address-line-2": "Ленинский пр-т, д. 169"},
                    "cityname": "г. Воронеж",
                    "phone": "(473) 239-62-25",
                    "work": {"time": "пн. - пт. с 10:00 до 19:00; сб. - вс. с 10:00 до 18:00", "day": ""},
                    "location": {"lat": 51.6929370072, "lng": 39.2682829499}
                },
                {"id": 663, "code": "vologda",
                    "name": "&quot;Интер&quot; ", "stationId": "0", "stationName": "",
                    "url": "/buy/inter272.html",
                    "department": "&quot;Интер&quot; ",
                    "images": '/upload/resize_cache/iblock/bce/153_113_1/1.JPG',
                    "address": {"address-line-1": " г. Вологда",
                        "address-line-2": "ул. Чехова, д. 27, ТЦ &quot;Панорама&quot; "},
                    "cityname": "г. Вологда",
                    "phone": "(8172) 787-337 доб. 3706 ",
                    "work": {"time": "с 10:00 до 19:00", "day": "Ежедневно"},
                    "location": {"lat": 59.212541187275, "lng": 39.885019361973}
                },
                {"id": 669, "code": "ivanovo",
                    "name": "&quot;Р.И.М.&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/r-i-m-48.html",
                    "department": "&quot;Р.И.М.&quot;",
                    "images": '/upload/resize_cache/iblock/a16/153_113_1/dsc04769.jpg',
                    "address": {"address-line-1": " г. Иваново",
                        "address-line-2": "пр-т Ленина,  д.138"},
                    "cityname": "г. Иваново",
                    "phone": "(4932) 37-60-28",
                    "work": {"time": "", "day": "Ежедневно"},
                    "location": {"lat": 57.0121298, "lng": 40.9714286}
                },
                {"id": 670, "code": "izhevsk",
                    "name": "&quot;Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona515.html",
                    "department": "&quot;Верона&quot;",
                    "images": '/upload/resize_cache/iblock/8e5/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Ижевск",
                        "address-line-2": "ул. 10 Лет Октября, д. 17а"},
                    "cityname": "г. Ижевск",
                    "phone": "(3412) 422-718",
                    "work": {"time": "пн - пт с 9:00 до 18:00", "day": ""},
                    "location": {"lat": 56.8733499, "lng": 53.21504}
                },
                {"id": 673, "code": "irkutsk",
                    "name": "&quot;Эталон&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/etalon212.html",
                    "department": "&quot;Эталон&quot;",
                    "images": '/upload/resize_cache/iblock/1ce/153_113_1/img_1563.jpg',
                    "address": {"address-line-1": " г. Иркутск",
                        "address-line-2": "ул.Партизанская, 63"},
                    "cityname": "г. Иркутск",
                    "phone": "(3952) 20-57-12, 66-40-47",
                    "work": {"time": "пн. - пт. с 9:00 до 18:00; сб. с 10:00 до 18:00; вс. с 10:00 до 16:00", "day": ""},
                    "location": {"lat": 52.2776168, "lng": 104.30676}
                },
                {"id": 674, "code": "kazan",
                    "name": "&quot;Мебель класс&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/mebel-klass10.html",
                    "department": "&quot;Мебель класс&quot;",
                    "images": '/upload/resize_cache/iblock/313/153_113_1/11.jpg',
                    "address": {"address-line-1": " г. Казань",
                        "address-line-2": "ул. Ибрагимова, 59"},
                    "cityname": "г. Казань",
                    "phone": "(843) 519-19-99",
                    "work": {"time": "пт. - сб. с 10:00 до 19:00; вс. с 10:00 до 18:00", "day": ""},
                    "location": {"lat": 55.8282695, "lng": 49.0936669}
                },
                {"id": 678, "code": "krasnodar",
                    "name": "&quot;VERONA design 1&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design-1639.html",
                    "department": "&quot;VERONA design 1&quot;",
                    "images": '/upload/resize_cache/iblock/d1a/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Краснодар",
                        "address-line-2": "ул. Северная, д. 300"},
                    "cityname": "г. Краснодар",
                    "phone": "(861) 255-52-95, 253-44-67",
                    "work": {"time": "пн. - пт.: с 10:00 до 19:00; сб. - вс.: с 10:00 до 18:00", "day": "Ежедневно"},
                    "location": {"lat": 45.0397638, "lng": 38.9787956}
                },
                {"id": 167, "code": "moskva",
                    "name": "VERONA design", "stationId": "144", "stationName": "Планерная",
                    "url": "/buy/verona-design-r-n-kurkino.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/a58/153_113_1/a021.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "ул. Соловьиная роща, д. 3"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 401-80-93",
                    "work": {"time": "10:00 - 20:00", "day": "по звонку"},
                    "location": {"lat": 55.8898819308, "lng": 37.3989826614}
                },
                {"id": 679, "code": "krasnodar",
                    "name": "&quot;VERONA design 2&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design-2719.html",
                    "department": "&quot;VERONA design 2&quot;",
                    "images": '/upload/resize_cache/iblock/3af/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Краснодар",
                        "address-line-2": "ул. Новороссийская, 230"},
                    "cityname": "г. Краснодар",
                    "phone": "(861) 210-13-78",
                    "work": {"time": "с 10:00 - до 21:00", "day": "Ежедневно"},
                    "location": {"lat": 45.0371221, "lng": 39.0495294}
                },
                {"id": 680, "code": "krasnoyarsk",
                    "name": "&quot;Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona762.html",
                    "department": "&quot;Верона&quot;",
                    "images": '/upload/resize_cache/iblock/e8e/153_113_1/jpg.jpeg',
                    "address": {"address-line-1": " г. Красноярск",
                        "address-line-2": " ул. Молокова, д. 17"},
                    "cityname": "г. Красноярск",
                    "phone": "(391) 277-57-21",
                    "work": {"time": "пн. - сб.: с 10:00 до 19:00; вс. выходной", "day": ""},
                    "location": {"lat": 56.039235574362, "lng": 92.902418375015}
                },
                {"id": 169, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "182", "stationName": "Киевская",
                    "url": "/buy/verona-mobili-tk-tri-kita-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/7fb/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Можайское ш., (2 км от МКАД), 5-й этаж, ТК &quot;Три Кита&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 971-83-97",
                    "work": {"time": "10:00 - 21:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7030321962, "lng": 37.3557686806}
                },
                {"id": 681, "code": "kursk",
                    "name": "&quot;Кухни Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/kukhni-verona62.html",
                    "department": "&quot;Кухни Верона&quot;",
                    "images": '/upload/resize_cache/iblock/2f2/153_113_1/14092010513.jpg',
                    "address": {"address-line-1": " г. Курск",
                        "address-line-2": "ул. Дружининская, 7а"},
                    "cityname": "г. Курск",
                    "phone": "(4712) 31-03-52, (910) 731-03-52",
                    "work": {"time": "пн - пт с 10:00 до 19:00; сб с10:00 до 17:00", "day": ""},
                    "location": {"lat": 51.7231894, "lng": 36.1780551}
                },
                {"id": 170, "code": "moskva",
                    "name": "VERONA design", "stationId": "179", "stationName": "Таганская",
                    "url": "/buy/verona-design-m-taganskaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/2fd/153_113_1/00.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "ул. Большие Каменщики, д. 6"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 911-94-86",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7371173781, "lng": 37.6542903614}
                },
                {"id": 171, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "150", "stationName": "Речной вокзал",
                    "url": "/buy/verona-mobili-tk-grand-i-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/779/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Ленинградское ш. (100 м от МКАД), 2 этаж, ТК &quot;Гранд&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 971-81-15",
                    "work": {"time": "10:00 - 21:00", "day": "Ежедневно"},
                    "location": {"lat": 55.885511415, "lng": 37.4378013611}
                },
                {"id": 683, "code": "makhachkala",
                    "name": "&quot;Аризона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/arizona994.html",
                    "department": "&quot;Аризона&quot;",
                    "images": '/upload/resize_cache/iblock/00f/153_113_1/img_2252.jpg',
                    "address": {"address-line-1": " г. Махачкала",
                        "address-line-2": "пр-т Гамидова, д.11"},
                    "cityname": "г. Махачкала",
                    "phone": "(8722) 67-24-14",
                    "work": {"time": "c 10:00 до 19:00", "day": "Ежедневно"},
                    "location": {"lat": 42.9783677, "lng": 47.4910661}
                },
                {"id": 173, "code": "moskva",
                    "name": "VERONA design", "stationId": "9971", "stationName": "Тропарево",
                    "url": "/buy/verona-design-m-yugo-zapadnaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/c7f/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Ленинский пр-т, д. 123"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 726-26-71; +7 499 726-28-61",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.6469289401, "lng": 37.4788981676}
                },
                {"id": 685, "code": "n-novgorod",
                    "name": "LA'VILLA", "stationId": "0", "stationName": "",
                    "url": "/buy/la-villa368.html",
                    "department": "LA'VILLA",
                    "images": '/upload/resize_cache/iblock/ce5/153_113_1/01.jpg',
                    "address": {"address-line-1": " г. Н. Новгород",
                        "address-line-2": "ул.Дунаева, д. 15"},
                    "cityname": "г. Н. Новгород",
                    "phone": "(831) 416-79-75",
                    "work": {"time": "пн. - сб.: с 10:00 до 19:00; вс. выходной", "day": ""},
                    "location": {"lat": 56.3163932, "lng": 44.0258731}
                },
                {"id": 174, "code": "moskva",
                    "name": "Дисконт Центр &quot;VERONA design&quot;", "stationId": "81", "stationName": "Тушинская",
                    "url": "/buy/diskont-tsentr-verona-design.html",
                    "department": "Дисконт Центр &quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/09a/153_113_1/00.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Волоколамское ш., д. 95"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 519-64-31",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.8308724721, "lng": 37.4022781849}
                },
                {"id": 175, "code": "moskva",
                    "name": "VERONA design", "stationId": "70", "stationName": "Университет",
                    "url": "/buy/verona-design-m-universitet.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/9dc/153_113_1/a007.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Мичуринский пр-т, д. 10, к. 1"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 932-61-67;  +7 963 724-97-45",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7040587165, "lng": 37.5088876693}
                },
                {"id": 176, "code": "moskva",
                    "name": "VERONA design", "stationId": "172", "stationName": "ВДНХ",
                    "url": "/buy/verona-design.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/964/153_113_1/a015.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Ярославское ш., д. 130, к. 1 (съезд с дублера)"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 287-04-02; +7 499 182-06-01",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.8732767, "lng": 37.7156571}
                },
                {"id": 177, "code": "moskva",
                    "name": "VERONA design", "stationId": "84", "stationName": "Полежаевская",
                    "url": "/buy/verona-design-m-polezhaevskaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/8cc/153_113_1/2.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "пр-т Маршала Жукова, д. 59"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 199-40-07",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7778099953, "lng": 37.4581003189}
                },
                {"id": 179, "code": "moskva",
                    "name": "VERONA design", "stationId": "174", "stationName": "Рижская",
                    "url": "/buy/verona-design-m-rizhskaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/e88/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "пр-т Мира, д. 79 (с ул. Гиляровского)"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 681-07-02",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7903404666, "lng": 37.6338815689}
                },
                {"id": 180, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "182", "stationName": "Киевская",
                    "url": "/buy/verona-mobili-tk-elit-stroy-materialy-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/7b9/153_113_1/33.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "50-й км. МКАД, 2 этаж, ТК &quot;ЭлитСтрой материалы&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 710-78-75",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.6833887584, "lng": 37.413201432}
                },
                {"id": 181, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "53", "stationName": "Домодедовская",
                    "url": "/buy/verona-mobili-tts-tvoy-dom-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/05f/153_113_1/000.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "24-й км. МКАД, 2-й этаж, ТК &quot;Твой Дом-Каширка&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 727-25-70",
                    "work": {"time": "10:00 - 21:00", "day": "Ежедневно"},
                    "location": {"lat": 55.586276608, "lng": 37.7196478844}
                },
                {"id": 693, "code": "omsk",
                    "name": "&quot;VERONA mobili&quot; ", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design888.html",
                    "department": "&quot;VERONA mobili&quot; ",
                    "images": '/upload/resize_cache/iblock/9f1/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Омск",
                        "address-line-2": "ул. 10 лет Октября, 182, корп.3, ТК &quot;КИТ-интерьер&quot;"},
                    "cityname": "г. Омск",
                    "phone": "(3812) 72-90-60; (962) 05-05-686  ",
                    "work": {"time": "с 10:00 до 19:00", "day": "Ежедневно"},
                    "location": {"lat": 54.9894830764, "lng": 73.4589457512}
                },
                {"id": 182, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "114", "stationName": "Мякинино",
                    "url": "/buy/verona-mobili-tts-tvoy-dom-krokus-siti-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/d0b/153_113_1/DSC00651.JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "66-й км. МКАД, 2-й этаж, ТК &quot;Твой Дом Мебель Крокус&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 972-48-72; +7 903 715-67-58",
                    "work": {"time": "10:00 - 22:00", "day": "Ежедневно"},
                    "location": {"lat": 55.8187408097, "lng": 37.3873758316}
                },
                {"id": 694, "code": "orenburg",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design212.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/7a0/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Оренбург",
                        "address-line-2": "Проспект Победы, д. 73/1"},
                    "cityname": "г. Оренбург",
                    "phone": "(3532) 45-00-55",
                    "work": {"time": "с 10:00 - до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 51.7719251, "lng": 55.103059}
                },
                {"id": 183, "code": "moskva",
                    "name": "VERONA design", "stationId": "105", "stationName": "Кутузовская",
                    "url": "/buy/verona-design-m-kutuzovskaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/d3a/153_113_1/a011.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Кутузовский пр-т, д. 35/30"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 249-05-02; +7 499 249-19-54",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7396628944, "lng": 37.5371932983}
                },
                {"id": 695, "code": "penza",
                    "name": "«21 Век»", "stationId": "0", "stationName": "",
                    "url": "/buy/21-vek360.html",
                    "department": "«21 Век»",
                    "images": '/upload/resize_cache/iblock/2b5/153_113_1/P1000854.JPG',
                    "address": {"address-line-1": " г. Пенза",
                        "address-line-2": "пр-т Победы 138, Мебельный салон «21 Век»"},
                    "cityname": "г. Пенза",
                    "phone": "(8412) 43-37-17; 43-32-02; (963) 107-47-46",
                    "work": {"time": "пн. - пт. с 10:00 до 19.00; сб. с 10:00 до 17:00", "day": ""},
                    "location": {"lat": 53.229324, "lng": 44.928328}
                },
                {"id": 184, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "6", "stationName": "Пражская",
                    "url": "/buy/verona-mobili-tk-armada-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/863/153_113_1/DSC04541.JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "ул. Кировоградская, д. 11, 4 этаж, ТК &quot;Армада&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 971-09-06",
                    "work": {"time": "10:00 - 22:00", "day": "Ежедневно"},
                    "location": {"lat": 55.6143517369, "lng": 37.6069380344}
                },
                {"id": 696, "code": "perm",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design410.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/5b6/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Пермь",
                        "address-line-2": "ул. 25 Октября, д. 18"},
                    "cityname": "г. Пермь",
                    "phone": "(342) 210-89-09",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 58.0137397, "lng": 56.2501769}
                },
                {"id": 185, "code": "moskva",
                    "name": "VERONA mobili", "stationId": "99", "stationName": "Новогиреево",
                    "url": "/buy/verona-mobili-tts-rio-iii-.html",
                    "department": "VERONA mobili",
                    "images": '/upload/resize_cache/iblock/32e/153_113_1/01.jpg',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "2-ой км МКАД, 3-й этаж, ТК &quot;РИО Реутов&quot;"},
                    "cityname": "г. Москва",
                    "phone": "+7 495 987-17-55",
                    "work": {"time": "10:00 - 22:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7655893581, "lng": 37.8449392319}
                },
                {"id": 186, "code": "moskva",
                    "name": "VERONA design", "stationId": "73", "stationName": "Фрунзенская",
                    "url": "/buy/verona-design-m-frunzenskaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/7ca/153_113_1/1.JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Комсомольский проспект, д. 36"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 242-61-43",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7237902038, "lng": 37.5761481865}
                },
                {"id": 698, "code": "pyatigorsk",
                    "name": "&quot;Домус&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/diskom131.html",
                    "department": "&quot;Домус&quot;",
                    "images": '/upload/resize_cache/iblock/b76/153_113_1/jpg.jpeg',
                    "address": {"address-line-1": " г. Пятигорск",
                        "address-line-2": "ул. Ермолова, д. 14, строение 7"},
                    "cityname": "г. Пятигорск",
                    "phone": "(8793) 40-48-71",
                    "work": {"time": "пн. - сб. с 10:00 до 19:00; вс. с 10:00 до 16:00", "day": ""},
                    "location": {"lat": 44.0442830324, "lng": 43.020336628}
                },
                {"id": 187, "code": "moskva",
                    "name": "VERONA design", "stationId": "150", "stationName": "Речной вокзал",
                    "url": "/buy/verona-design-m-rechnoy-vokzal.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/828/153_113_1/PICT0035.JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Ленинградское шоссе, д. 100"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 401-01-15",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.8578587262, "lng": 37.4690194153}
                },
                {"id": 699, "code": "rostov-na-donu",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design-146.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/96c/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Ростов-на-Дону",
                        "address-line-2": "ул. Красноармейская, д. 298/81"},
                    "cityname": "г. Ростов-на-Дону",
                    "phone": "(863) 200-32-23",
                    "work": {"time": "", "day": "пн. - сб. с 10:00 до 19:00; вс. с 10:00 до 17:00"},
                    "location": {"lat": 47.2332413, "lng": 39.7389013}
                },
                {"id": 700, "code": "rostov-na-donu",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design-2170.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/070/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Ростов-на-Дону",
                        "address-line-2": "площадь Гагарина, д.6 / 87"},
                    "cityname": "г. Ростов-на-Дону",
                    "phone": "(863) 227-24-24, 227-24-34",
                    "work": {"time": "", "day": "пн. - сб. с 10:00 до 19:00; вс. с 10:00 до 17:00"},
                    "location": {"lat": 47.2355428, "lng": 39.7150427}
                },
                {"id": 704, "code": "samara",
                    "name": "&quot;VERONA design&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-design857.html",
                    "department": "&quot;VERONA design&quot;",
                    "images": '/upload/resize_cache/iblock/5d3/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Самара",
                        "address-line-2": "ул. Галактионовская, д. 277"},
                    "cityname": "г. Самара",
                    "phone": "(846) 337-41-62, 337-41-63",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 53.2051950907, "lng": 50.1210708705}
                },
                {"id": 713, "code": "saransk",
                    "name": "&quot;Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona37.html",
                    "department": "&quot;Верона&quot;",
                    "images": '/upload/resize_cache/iblock/d2a/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Саранск",
                        "address-line-2": "Коммунистическая, д,123А  "},
                    "cityname": "г. Саранск",
                    "phone": "(8342) 23-40-59",
                    "work": {"time": "пн. - сб. с 10:00 до 19:00; с 10:00 до 17:00", "day": ""},
                    "location": {"lat": 54.1857673, "lng": 45.157901}
                },
                {"id": 714, "code": "smolensk",
                    "name": "VERONA", "stationId": "0", "stationName": "",
                    "url": "/buy/verona416.html",
                    "department": "VERONA",
                    "images": '/upload/resize_cache/iblock/9be/153_113_1/DSC06962.jpg',
                    "address": {"address-line-1": " г. Смоленск",
                        "address-line-2": "ул. Бабушкина д.1, ТЦ &quot;Искра&quot; 2"},
                    "cityname": "г. Смоленск",
                    "phone": "(4812) 404-724",
                    "work": {"time": "пн - пт с 10:00 до 19:00, сб - вс с 11:00 до 18:00", "day": ""},
                    "location": {"lat": 54.7677375, "lng": 32.04233}
                },
                {"id": 716, "code": "sochi",
                    "name": "&quot;VERONA mobili&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili404.html",
                    "department": "&quot;VERONA mobili&quot;",
                    "images": '/upload/resize_cache/iblock/adb/153_113_1/4.jpg',
                    "address": {"address-line-1": " г. Сочи",
                        "address-line-2": "ул. Пластунская, д. 81 (1 этаж)"},
                    "cityname": "г. Сочи",
                    "phone": "(8622) 272-004; (8622) 272-002",
                    "work": {"time": "пн. - сб.: с 10:00 до 19:00; вс.: с 10:00 до 16:00", "day": ""},
                    "location": {"lat": 43.6101679382, "lng": 39.7376480699}
                },
                {"id": 721, "code": "staryy-oskol",
                    "name": "&quot;Нефертити&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/nefertiti774.html",
                    "department": "&quot;Нефертити&quot;",
                    "images": '/upload/resize_cache/iblock/505/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Старый Оскол",
                        "address-line-2": "мкрн. Восточный, д.13  "},
                    "cityname": "г. Старый Оскол",
                    "phone": "(4725) 42-37-45",
                    "work": {"time": "с 10:00 до 19:00", "day": "Ежедневно"},
                    "location": {"lat": 51.3, "lng": 37.85}
                },
                {"id": 722, "code": "surgut",
                    "name": "&quot;Интермебель&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/intermebel394.html",
                    "department": "&quot;Интермебель&quot;",
                    "images": '/upload/resize_cache/iblock/b97/153_113_1/2c0x8303.jpg',
                    "address": {"address-line-1": " г. Сургут",
                        "address-line-2": "ул. Аэрофлотская, д.6"},
                    "cityname": "г. Сургут",
                    "phone": "(3462) 37-93-89",
                    "work": {"time": "пн. - сб. с 10:00 до 19:00; вс. с 11:00 до 17:00", "day": ""},
                    "location": {"lat": 61.2666667, "lng": 73.4}
                },
                {"id": 724, "code": "tambov",
                    "name": "&quot;Ателье Мебели&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/atele-mebeli662.html",
                    "department": "&quot;Ателье Мебели&quot;",
                    "images": '/upload/resize_cache/iblock/aca/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Тамбов",
                        "address-line-2": "ул.Советская, д.37  "},
                    "cityname": "г. Тамбов",
                    "phone": "(4752) 76-00-56",
                    "work": {"time": "пн - сб с 10:00 до 20:00; вс с 10:00 до 17:00", "day": ""},
                    "location": {"lat": 52.7184495969, "lng": 41.4578533173}
                },
                {"id": 725, "code": "tomsk",
                    "name": "&quot;VERONA mobili&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/verona-mobili605.html",
                    "department": "&quot;VERONA mobili&quot;",
                    "images": '/upload/resize_cache/iblock/be9/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Томск",
                        "address-line-2": "пер. Дербышевский, д. 22 ТЦ &quot;НОКС&quot;"},
                    "cityname": "г. Томск",
                    "phone": "(3822) 40-63-90, 40-58-72",
                    "work": {"time": "пн. - сб.: с 10:00 до 20:00; вс.: с 10:00 до 19:00", "day": ""},
                    "location": {"lat": 56.5, "lng": 84.9666667}
                },
                {"id": 726, "code": "tomsk",
                    "name": "&quot;Кухни Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/kukhni-verona209.html",
                    "department": "&quot;Кухни Верона&quot;",
                    "images": '/upload/resize_cache/iblock/ce0/153_113_1/DSC00025.jpg',
                    "address": {"address-line-1": " г. Томск",
                        "address-line-2": "пер. Типографский, 1а (за главным корпусом ТУСУР)"},
                    "cityname": "г. Томск",
                    "phone": "(3822) 53-58-00",
                    "work": {"time": "пн. - пт. с 10:00 до 19:00, сб. 11:00 до 17:00, вс. выходной", "day": "Ежедневно"},
                    "location": {"lat": 56.4759079666, "lng": 84.9609875679}
                },
                {"id": 727, "code": "tula",
                    "name": "&quot;Люкс&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/tsentr-kukhni72.html",
                    "department": "&quot;Люкс&quot;",
                    "images": '/upload/resize_cache/iblock/960/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Тула",
                        "address-line-2": "ул. Пушкинская, д. 58А"},
                    "cityname": "г. Тула",
                    "phone": "(4872) 702-899",
                    "work": {"time": "пн. - сб. с 10:00 до 19:00, вс. выходной", "day": "(4872) 25-65-75"},
                    "location": {"lat": 54.191736761632, "lng": 37.599999904633}
                },
                {"id": 728, "code": "tula",
                    "name": "&quot;Таурус&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/taurus728.html",
                    "department": "&quot;Таурус&quot;",
                    "images": '/upload/resize_cache/iblock/441/153_113_1/jpg.jpeg',
                    "address": {"address-line-1": " г. Тула",
                        "address-line-2": "ул.Коминтерна, 24-Б"},
                    "cityname": "г. Тула",
                    "phone": "(4872) 36-97-53",
                    "work": {"time": "пн - пт с 10:00 до 20:00, сб - вс с 10:00 до 19:00", "day": ""},
                    "location": {"lat": 54.2009592, "lng": 37.5994914}
                },
                {"id": 730, "code": "tyumen",
                    "name": "&quot;Дизайн-Интерьер&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/dizayn-interer117.html",
                    "department": "&quot;Дизайн-Интерьер&quot;",
                    "images": '/upload/resize_cache/iblock/7a8/153_113_1/img_0294.jpg',
                    "address": {"address-line-1": " г. Тюмень",
                        "address-line-2": "ул. Малыгина, д. 4"},
                    "cityname": "г. Тюмень",
                    "phone": "(3452) 63-34-57",
                    "work": {"time": "пн. - пт. с 10:00 до 19:00; сб. - вс. с 11:00 до 18:00", "day": ""},
                    "location": {"lat": 57.142058, "lng": 65.5532028}
                },
                {"id": 731, "code": "tyumen",
                    "name": "&quot;CASANOVA&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/casanova897.html",
                    "department": "&quot;CASANOVA&quot;",
                    "images": '/upload/resize_cache/iblock/d2b/153_113_1/DSC08174.jpg',
                    "address": {"address-line-1": " г. Тюмень",
                        "address-line-2": "ул. Комсомольская, д. 58/4"},
                    "cityname": "г. Тюмень",
                    "phone": "(3452) 63-17-42",
                    "work": {"time": "пн. - пт. с 10:00 до 19:00; сб. - вс. с 11:00 до 18:00", "day": ""},
                    "location": {"lat": 57.1570041, "lng": 65.5556268}
                },
                {"id": 734, "code": "cheboksary",
                    "name": "&quot;Мебель Верона&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/mebel-verona305.html",
                    "department": "&quot;Мебель Верона&quot;",
                    "images": '/upload/resize_cache/iblock/fc3/153_113_1/111.jpg',
                    "address": {"address-line-1": " г. Чебоксары",
                        "address-line-2": "пр-т Максима Горького, д. 26"},
                    "cityname": "г. Чебоксары",
                    "phone": "(8352) 41-03-14",
                    "work": {"time": "пн - пт с 9:00 до 19:00; сб с 10:00 до 18:00; вс с 10:00 до 15:00", "day": ""},
                    "location": {"lat": 56.1492404, "lng": 47.1802675}
                },
                {"id": 735, "code": "chelyabinsk",
                    "name": "Центр Интерьера &quot;Магнит&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/magnit839.html",
                    "department": "Центр Интерьера &quot;Магнит&quot;",
                    "images": '/upload/resize_cache/iblock/200/153_113_1/jpg.jpeg',
                    "address": {"address-line-1": " г. Челябинск",
                        "address-line-2": "ул. Труда, д. 185а (2 этаж, секция 213; 3 этаж, секция 315)"},
                    "cityname": "г. Челябинск",
                    "phone": "(351) 270-96-51, 271-58-63",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.1690285997, "lng": 61.373826838}
                },
                {"id": 736, "code": "chelyabinsk",
                    "name": "Дом Интерьера", "stationId": "0", "stationName": "",
                    "url": "/buy/tvk-koltso919.html",
                    "department": "Дом Интерьера",
                    "images": '/upload/resize_cache/iblock/78c/153_113_1/01.jpg',
                    "address": {"address-line-1": " г. Челябинск",
                        "address-line-2": "ул. Бр.Кашириных, д. 130"},
                    "cityname": "г. Челябинск",
                    "phone": "8 (351) 211-06-28",
                    "work": {"time": "с 10:00 до 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.1721893918, "lng": 61.3012969494}
                },
                {"id": 737, "code": "yuzhno-sakhalinsk",
                    "name": "&quot;Дом мебели&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/dom-mebeli681.html",
                    "department": "&quot;Дом мебели&quot;",
                    "images": '/upload/resize_cache/iblock/67a/153_113_1/1.jpg',
                    "address": {"address-line-1": " г. Южно-Сахалинск",
                        "address-line-2": "ул. Хабаровская, д. 84"},
                    "cityname": "г. Южно-Сахалинск",
                    "phone": "(4242) 72-26-81",
                    "work": {"time": "пн - пт с 9:30 до 18:30, сб - вс с 10:00 до 16:00", "day": ""},
                    "location": {"lat": 46.9666667, "lng": 142.7333333}
                },
                {"id": 739, "code": "yakutsk",
                    "name": "&quot;Омич&quot;", "stationId": "0", "stationName": "",
                    "url": "/buy/omich580.html",
                    "department": "&quot;Омич&quot;",
                    "images": '/upload/resize_cache/iblock/fcd/153_113_1/izobrawenie_019.jpg',
                    "address": {"address-line-1": " г. Якутск",
                        "address-line-2": "ул. Якутская 36"},
                    "cityname": "г. Якутск",
                    "phone": "8 (4112) 44-75-49",
                    "work": {"time": "пн. - сб. с 10:00 до 18:00; вс. с 10:00 до 17:00", "day": ""},
                    "location": {"lat": 62.0620563, "lng": 129.7146052}
                },
                {"id": 9704, "code": "moskva",
                    "name": "VERONA design", "stationId": "68", "stationName": "Курская",
                    "url": "/buy/verona-design-basmannaya.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/879/153_113_1/DSCN2581.JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Старая Басманная, д. 15, стр. 2"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 261-32-60; +7 963 724-97-43",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.7655652147, "lng": 37.6599392295}
                },
                {"id": 10223, "code": "moskva",
                    "name": "VERONA design", "stationId": "70", "stationName": "Университет",
                    "url": "/buy/verona-design-leninsky.html",
                    "department": "VERONA design",
                    "images": '/upload/resize_cache/iblock/c07/153_113_1/DSC08290 (1).JPG',
                    "address": {"address-line-1": " г. Москва",
                        "address-line-2": "Ленинский проспект, дом 60/2"},
                    "cityname": "г. Москва",
                    "phone": "+7 499 727-04-23",
                    "work": {"time": "10:00 - 20:00", "day": "Ежедневно"},
                    "location": {"lat": 55.696145754189, "lng": 37.558232545853}
                }]
        }
    };
})();
